const eventTriggers = {
	'area': {
		'Act 1': {
			"the twilight strand": "The Twilight Strand",
			"lioneye's watch": "Lioneye's Watch",
			"the coast": "The Coast",
			"the tidal island": "The Tidal Island",
			"the mud flats": "The Mud Flats",
			"the fetid pool": "The Fetid Pool",
			"the submerged passage": "The Submerged Passage",
			"the flooded depths": "The Flooded Depths",
			"the ledge": "The Ledge",
			"the climb": "The Climb",
			"the lower prison": "The Lower Prison",
			"the upper prison": "The Upper Prison",
			"prisoner's gate": "Prisoner's Gate",
			"the ship graveyard": "The Ship Graveyard",
			"the ship graveyard cave": "The Ship Graveyard Cave",
			"the cavern of wrath": "The Cavern of Wrath",
			"the cavern of anger": "The Cavern of Anger",
		},
		'Act 2': {
			"the southern forest": "The Southern Forest",
			"the forest encampment": "The Forest Encampment",
			"the old fields": "The Old Fields",
			"the den": "The Den",
			"the riverways": "The Riverways",
			"the crossroads": "The Crossroads",
			"the broken bridge": "The Broken Bridge",
			"chamber of sins level 1": "Chamber of Sins Level 1",
			"chamber of sins level 2": "Chamber of Sins Level 2",
			"the fellshrine ruins": "The Fellshrine Ruins",
			"the crypt level 1": "The Crypt Level 1",
			"the crypt level 2": "The Crypt Level 2",
			"the western forest": "The Western Forest",
			"weaver's chambers": "Weaver's Chambers",
			"the wetlands": "The Wetlands",
			"vaal ruins": "Vaal Ruins",
			"northern forest": "Northern Forest",
			"the dread thicket": "The Dread Thicket",
			"the caverns": "The Caverns",
			"ancient pyramid": "Ancient Pyramid",
		},
		'Act 3': {
			"the city of sarn": "The City of Sarn",
			"the sarn encampment": "The Sarn Encampment",
			"the slums": "The Slums",
			"the crematorium": "The Crematorium",
			"the sewers": "The Sewers",
			"the marketplace": "The Marketplace",
			"the ebony barracks": "The Ebony Barracks",
			"the catacombs": "The Catacombs",
			"the battlefront": "The Battlefront",
			"lunaris temple level 1": "Lunaris Temple Level 1",
			"lunaris temple level 2": "Lunaris Temple Level 2",
			"solaris temple level 1": "Solaris Temple Level 1",
			"solaris temple level 2": "Solaris Temple Level 2",
			"the docks": "The Docks",
			"the imperial gardens": "The Imperial Gardens",
			"the library": "The Library",
			"the archives": "The Archives",
			"the sceptre of god": "The Sceptre of God",
			"the upper sceptre of god": "The Upper Sceptre of God",
		},
		'Act 4': {
			"the aqueduct": "The Aqueduct",
			"highgate": "Highgate",
			"the dried lake": "The Dried Lake",
			"the mines level 1": "The Mines Level 1",
			"the mines level 2": "The Mines Level 2",
			"the crystal veins": "The Crystal Veins",
			"daresso's dream": "Daresso's Dream",
			"kaom's dream": "Kaom's Dream",
			"the grand arena": "The Grand Arena",
			"kaom's stronghold": "Kaom's Stronghold",
			"belly of the beast level 1": "Belly of the Beast Level 1",
			"belly of the beast level 2": "Belly of the Beast Level 2",
			"the harvest": "The Harvest",
			"the ascent": "The Ascent",
		},
		'Act 5': {
			"the slave pens": "The Slave Pens",
			"overseer's tower": "Overseer's Tower",
			"the control blocks": "The Control Blocks",
			"oriath square": "Oriath Square",
			"the templar courts": "The Templar Courts",
			"the chamber of innocence": "The Chamber of Innocence",
			"the torched courts": "The Torched Courts",
			"the ruined square": "The Ruined Square",
			"the cathedral rooftop": "The Cathedral Rooftop",
			"the reliquary": "The Reliquary",
			"the ossuary": "The Ossuary",
		},
		'Act 6': {
			"the twilight strand": "The Twilight Strand",
			"lioneye's watch": "Lioneye's Watch",
			"the coast": "The Coast",
			"the tidal island": "The Tidal Island",
			"the mud flats": "The Mud Flats",
			"the karui fortress": "The Karui Fortress",
			"the ridge": "The Ridge",
			"the lower prison": "The Lower Prison",
			"shavronne's tower": "Shavronne's Tower",
			"prisoner's gate": "Prisoner's Gate",
			"the western forest": "The Western Forest",
			"the riverways": "The Riverways",
			"the wetlands": "The Wetlands",
			"the southern forest": "The Southern Forest",
			"the cavern of anger": "The Cavern of Anger",
			"the beacon": "The Beacon",
			"the brine king's reef": "The Brine King's Reef",
		},
		'Act 7': {
			"the bridge encampment": "The Bridge Encampment",
			"the broken bridge": "The Broken Bridge",
			"the crossroads": "The Crossroads",
			"the fellshrine ruins": "The Fellshrine Ruins",
			"the crypt": "The Crypt",
			"the chamber of sins level 1": "The Chamber of Sins Level 1",
			"maligaro's sanctum": "Maligaro's Sanctum",
			"the chamber of sins level 2": "The Chamber of Sins Level 2",
			"the den": "The Den",
			"the ashen fields": "The Ashen Fields",
			"the northern forest": "The Northern Forest",
			"the dread thicket": "The Dread Thicket",
			"the causeway": "The Causeway",
			"the vaal city": "The Vaal City",
			"the temple of decay level 1": "The Temple of Decay Level 1",
			"the temple of decay level 2": "The Temple of Decay Level 2",
		},
		'Act 8': {
			"the sarn ramparts": "The Sarn Ramparts",
			"the sarn encampment": "The Sarn Encampment",
			"the toxic conduits": "The Toxic Conduits",
			"doedre's cesspool": "Doedre's Cesspool",
			"the grand promenade": "The Grand Promenade",
			"the quay": "The Quay",
			"the grain gate": "The Grain Gate",
			"the bath house": "The Bath House",
			"the high gardens": "The High Gardens",
			"the imperial fields": "The Imperial Fields",
			"the lunaris concourse": "The Lunaris Concourse",
			"the solaris temple level 1": "The Solaris Temple Level 1",
			"the solaris temple level 2": "The Solaris Temple Level 2",
			"the solaris concourse": "The Solaris Concourse",
			"the lunaris temple level 1": "The Lunaris Temple Level 1",
			"the lunaris temple level 2": "The Lunaris Temple Level 2",
			"the harbour bridge": "The Harbour Bridge",
		},
		'Act 9': {
			"the blood aqueduct": "The Blood Aqueduct",
			"highgate": "Highgate",
			"the descent": "The Descent",
			"the vastiri desert": "The Vastiri Desert",
			"the oasis": "The Oasis",
			"the foothills": "The Foothills",
			"the boiling lake": "The Boiling Lake",
			"the tunnel": "The Tunnel",
			"the quarry": "The Quarry",
			"the refinery": "The Refinery",
			"the belly of the beast": "The Belly of the Beast",
			"the rotting core": "The Rotting Core",
		},
		'Act 10': {
			"oriath docks": "Oriath Docks",
			"the cathedral rooftop": "The Cathedral Rooftop",
			"the ravaged square": "The Ravaged Square",
			"the ossuary": "The Ossuary",
			"the torched courts": "The Torched Courts",
			"the desecrated chambers": "The Desecrated Chambers",
			"the reliquary": "The Reliquary",
			"the control blocks": "The Control Blocks",
			"the canals": "The Canals",
			"the feeding trough": "The Feeding Trough",
		},
		'epilogue': {
			"oriath": "Oriath",
			"the templar laboratory": "The Templar Laboratory",
		}
	},
	'level': {
		"2": "2", "3": "3", "4": "4", "5": "5", "6": "6", "7": "7", "8": "8", "9": "9", "10": "10",
		"11": "11", "12": "12", "13": "13", "14": "14", "15": "15", "16": "16", "17": "17", "18": "18", "19": "19", "20": "20",
		"21": "21", "22": "22", "23": "23", "24": "24", "25": "25", "26": "26", "27": "27", "28": "28", "29": "29", "30": "30",
		"31": "31", "32": "32", "33": "33", "34": "34", "35": "35", "36": "36", "37": "37", "38": "38", "39": "39", "40": "40",
		"41": "41", "42": "42", "43": "43", "44": "44", "45": "45", "46": "46", "47": "47", "48": "48", "49": "49", "50": "50",
		"51": "51", "52": "52", "53": "53", "54": "54", "55": "55", "56": "56", "57": "57", "58": "58", "59": "59", "60": "60",
		"61": "61", "62": "62", "63": "63", "64": "64", "65": "65", "66": "66", "67": "67", "68": "68", "69": "69", "70": "70",
		"71": "71", "72": "72", "73": "73", "74": "74", "75": "75", "76": "76", "77": "77", "78": "78", "79": "79", "80": "80",
		"81": "81", "82": "82", "83": "83", "84": "84", "85": "85", "86": "86", "87": "87", "88": "88", "89": "89", "90": "90",
		"91": "91", "92": "92", "93": "93", "94": "94", "95": "95", "96": "96", "97": "97", "98": "98", "99": "99", "100": "100"
	},
	// 'kill': {
	// 	'Kitava': {
	// 		'act5': "You have been permanently weakened by Kitava's cruel affliction. You now have -30% to all Resistances",
	// 		'act10': "You have been permanently weakened by Kitava's merciless affliction. You now have a total of -60% to all Resistances.",
	// 	}
	// },
	'item': {
		'amulet': 'Amulet',
		'belt': 'Belt',
		'bodyArmour': 'Body Armour',
		'boots': 'Boots',
		'flask': 'Flask',
		'gloves': 'Gloves',
		'helm': 'Helm',
		'ring': 'Ring',
		'weapon': 'Weapon'
	}
};

export default eventTriggers;