const eventTriggers = {
	'area': {
		'Act 1': {
			"The Twilight Strand": "The Twilight Strand",
			"Lioneye's Watch": "Lioneye's Watch",
			"The Coast": "The Coast",
			"The Tidal Island": "The Tidal Island",
			"The Mud Flats": "The Mud Flats",
			"The Fetid Pool": "The Fetid Pool",
			"The Submerged Passage": "The Submerged Passage",
			"The Flooded Depths": "The Flooded Depths",
			"The Ledge": "The Ledge",
			"The Climb": "The Climb",
			"The Lower Prison": "The Lower Prison",
			"The Upper Prison": "The Upper Prison",
			"Prisoner's Gate": "Prisoner's Gate",
			"The Ship Graveyard": "The Ship Graveyard",
			"The Ship Graveyard Cave": "The Ship Graveyard Cave",
			"The Cavern of Wrath": "The Cavern of Wrath",
			"The Cavern of Anger": "The Cavern of Anger",
		},
		'Act 2': {
			"The Southern Forest": "The Southern Forest",
			"The Forest Encampment": "The Forest Encampment",
			"The Old Fields": "The Old Fields",
			"The Den": "The Den",
			"The Riverways": "The Riverways",
			"The Crossroads": "The Crossroads",
			"The Broken Bridge": "The Broken Bridge",
			"Chamber of Sins Level 1": "Chamber of Sins Level 1",
			"Chamber of Sins Level 2": "Chamber of Sins Level 2",
			"The Fellshrine Ruins": "The Fellshrine Ruins",
			"The Crypt Level 1": "The Crypt Level 1",
			"The Crypt Level 2": "The Crypt Level 2",
			"The Western Forest": "The Western Forest",
			"Weaver's Chambers": "Weaver's Chambers",
			"The Wetlands": "The Wetlands",
			"Vaal Ruins": "Vaal Ruins",
			"Northern Forest": "Northern Forest",
			"The Dread Thicket": "The Dread Thicket",
			"The Caverns": "The Caverns",
			"Ancient Pyramid": "Ancient Pyramid",
		},
		'Act 3': {
			"The City of Sarn": "The City of Sarn",
			"The Sarn Encampment": "The Sarn Encampment",
			"The Slums": "The Slums",
			"The Crematorium": "The Crematorium",
			"The Sewers": "The Sewers",
			"The Marketplace": "The Marketplace",
			"The Ebony Barracks": "The Ebony Barracks",
			"The Catacombs": "The Catacombs",
			"The Battlefront": "The Battlefront",
			"Lunaris Temple Level 1": "Lunaris Temple Level 1",
			"Lunaris Temple Level 2": "Lunaris Temple Level 2",
			"Solaris Temple Level 1": "Solaris Temple Level 1",
			"Solaris Temple Level 2": "Solaris Temple Level 2",
			"The Docks": "The Docks",
			"The Imperial Gardens": "The Imperial Gardens",
			"The Library": "The Library",
			"The Archives": "The Archives",
			"The Sceptre of God": "The Sceptre of God",
			"The Upper Sceptre of God": "The Upper Sceptre of God",
		},
		'Act 4': {
			"The Aqueduct": "The Aqueduct",
			"Highgate": "Highgate",
			"The Dried Lake": "The Dried Lake",
			"The Mines Level 1": "The Mines Level 1",
			"The Mines Level 2": "The Mines Level 2",
			"The Crystal Veins": "The Crystal Veins",
			"Daresso's Dream": "Daresso's Dream",
			"Kaom's Dream": "Kaom's Dream",
			"The Grand Arena": "The Grand Arena",
			"Kaom's Stronghold": "Kaom's Stronghold",
			"Belly of the Beast Level 1": "Belly of the Beast Level 1",
			"Belly of the Beast Level 2": "Belly of the Beast Level 2",
			"The Harvest": "The Harvest",
			"The Ascent": "The Ascent",
		},
		'Act 5': {
			"The Slave Pens": "The Slave Pens",
			"Overseer's Tower": "Overseer's Tower",
			"The Control Blocks": "The Control Blocks",
			"Oriath Square": "Oriath Square",
			"The Templar Courts": "The Templar Courts",
			"The Chamber of Innocence": "The Chamber of Innocence",
			"The Torched Courts": "The Torched Courts",
			"The Ruined Square": "The Ruined Square",
			"The Cathedral Rooftop": "The Cathedral Rooftop",
			"The Reliquary": "The Reliquary",
			"The Ossuary": "The Ossuary",
		},
		'Act 6': {
			"The Twilight Strand": "The Twilight Strand",
			"Lioneye's Watch": "Lioneye's Watch",
			"The Coast": "The Coast",
			"The Tidal Island": "The Tidal Island",
			"The Mud Flats": "The Mud Flats",
			"The Karui Fortress": "The Karui Fortress",
			"The Ridge": "The Ridge",
			"The Lower Prison": "The Lower Prison",
			"Shavronne's Tower": "Shavronne's Tower",
			"Prisoner's Gate": "Prisoner's Gate",
			"The Western Forest": "The Western Forest",
			"The Riverways": "The Riverways",
			"The Wetlands": "The Wetlands",
			"The Southern Forest": "The Southern Forest",
			"The Cavern of Anger": "The Cavern of Anger",
			"The Beacon": "The Beacon",
			"The Brine King's Reef": "The Brine King's Reef",
		},
		'Act 7': {
			"The Bridge Encampment": "The Bridge Encampment",
			"The Broken Bridge": "The Broken Bridge",
			"The Crossroads": "The Crossroads",
			"The Fellshrine Ruins": "The Fellshrine Ruins",
			"The Crypt": "The Crypt",
			"The Chamber of Sins Level 1": "The Chamber of Sins Level 1",
			"Maligaro's Sanctum": "Maligaro's Sanctum",
			"The Chamber of Sins Level 2": "The Chamber of Sins Level 2",
			"The Den": "The Den",
			"The Ashen Fields": "The Ashen Fields",
			"The Northern Forest": "The Northern Forest",
			"The Dread Thicket": "The Dread Thicket",
			"The Causeway": "The Causeway",
			"The Vaal City": "The Vaal City",
			"The Temple of Decay Level 1": "The Temple of Decay Level 1",
			"The Temple of Decay Level 2": "The Temple of Decay Level 2",
		},
		'Act 8': {
			"The Sarn Ramparts": "The Sarn Ramparts",
			"The Sarn Encampment": "The Sarn Encampment",
			"The Toxic Conduits": "The Toxic Conduits",
			"Doedre's Cesspool": "Doedre's Cesspool",
			"The Grand Promenade": "The Grand Promenade",
			"The Quay": "The Quay",
			"The Grain Gate": "The Grain Gate",
			"The Bath House": "The Bath House",
			"The High Gardens": "The High Gardens",
			"The Imperial Fields": "The Imperial Fields",
			"The Lunaris Concourse": "The Lunaris Concourse",
			"The Solaris Temple Level 1": "The Solaris Temple Level 1",
			"The Solaris Temple Level 2": "The Solaris Temple Level 2",
			"The Solaris Concourse": "The Solaris Concourse",
			"The Lunaris Temple Level 1": "The Lunaris Temple Level 1",
			"The Lunaris Temple Level 2": "The Lunaris Temple Level 2",
			"The Harbour Bridge": "The Harbour Bridge",
		},
		'Act 9': {
			"The Blood Aqueduct": "The Blood Aqueduct",
			"Highgate": "Highgate",
			"The Descent": "The Descent",
			"The Vastiri Desert": "The Vastiri Desert",
			"The Oasis": "The Oasis",
			"The Foothills": "The Foothills",
			"The Boiling Lake": "The Boiling Lake",
			"The Tunnel": "The Tunnel",
			"The Quarry": "The Quarry",
			"The Refinery": "The Refinery",
			"The Belly of the Beast": "The Belly of the Beast",
			"The Rotting Core": "The Rotting Core",
		},
		'Act 10': {
			"Oriath Docks": "Oriath Docks",
			"The Cathedral Rooftop": "The Cathedral Rooftop",
			"The Ravaged Square": "The Ravaged Square",
			"The Ossuary": "The Ossuary",
			"The Torched Courts": "The Torched Courts",
			"The Desecrated Chambers": "The Desecrated Chambers",
			"The Reliquary": "The Reliquary",
			"The Control Blocks": "The Control Blocks",
			"The Canals": "The Canals",
			"The Feeding Trough": "The Feeding Trough",
		},
		'epilogue': {
			"Oriath": "Oriath",
			"The Templar Laboratory": "The Templar Laboratory",
		}
	},
	'level': {
		"1": "1", "2": "2", "3": "3", "4": "4", "5": "5", "6": "6", "7": "7", "8": "8", "9": "9", "10": "10",
		"11": "11", "12": "12", "13": "13", "14": "14", "15": "15", "16": "16", "17": "17", "18": "18", "19": "19", "20": "20",
		"21": "21", "22": "22", "23": "23", "24": "24", "25": "25", "26": "26", "27": "27", "28": "28", "29": "29", "30": "30",
		"31": "31", "32": "32", "33": "33", "34": "34", "35": "35", "36": "36", "37": "37", "38": "38", "39": "39", "40": "40",
		"41": "41", "42": "42", "43": "43", "44": "44", "45": "45", "46": "46", "47": "47", "48": "48", "49": "49", "50": "50",
		"51": "51", "52": "52", "53": "53", "54": "54", "55": "55", "56": "56", "57": "57", "58": "58", "59": "59", "60": "60",
		"61": "61", "62": "62", "63": "63", "64": "64", "65": "65", "66": "66", "67": "67", "68": "68", "69": "69", "70": "70",
		"71": "71", "72": "72", "73": "73", "74": "74", "75": "75", "76": "76", "77": "77", "78": "78", "79": "79", "80": "80",
		"81": "81", "82": "82", "83": "83", "84": "84", "85": "85", "86": "86", "87": "87", "88": "88", "89": "89", "90": "90",
		"91": "91", "92": "92", "93": "93", "94": "94", "95": "95", "96": "96", "97": "97", "98": "98", "99": "99", "100": "100"
	},
	// 'kill': {
	// 	'Kitava': {
	// 		'act5': "You have been permanently weakened by Kitava's cruel affliction. You now have -30% to all Resistances",
	// 		'act10': "You have been permanently weakened by Kitava's merciless affliction. You now have a total of -60% to all Resistances.",
	// 	}
	// },
	'item': {
		'amulet': 'Amulet',
		'belt': 'Belt',
		'bodyArmour': 'Body Armour',
		'boots': 'Boots',
		'flask': 'Flask',
		'gloves': 'Gloves',
		'helm': 'Helm',
		'ring': 'Ring',
		'weapon': 'Weapon'
	}
};

export default eventTriggers;