const eventTriggers = {
	'area': {
		'act1': {
			"The Twilight Strand",
			"Lioneye's Watch",
			"The Coast",
			"The Tidal Island",
			"The Mud Flats",
			"The Fetid Pool",
			"The Submerged Passage",
			"The Flooded Depths",
			"The Ledge",
			"The Climb",
			"The Lower Prison",
			"The Upper Prison",
			"Prisoner's Gate",
			"The Ship Graveyard",
			"The Ship Graveyard Cave",
			"The Cavern of Wrath",
			"The Cavern of Anger",
		},
		'act2': {
			"The Southern Forest",
			"The Forest Encampment",
			"The Old Fields",
			"The Den",
			"The Riverways",
			"The Crossroads",
			"The Broken Bridge",
			"Chamber of Sins Level 1",
			"Chamber of Sins Level 2",
			"The Fellshrine Ruins",
			"The Crypt Level 1",
			"The Crypt Level 2",
			"The Western Forest",
			"Weaver's Chambers",
			"The Wetlands",
			"Vaal Ruins",
			"Northern Forest",
			"The Dread Thicket",
			"The Caverns",
			"Ancient Pyramid",
		},
		'act3': {
			"The City of Sarn",
			"The Sarn Encampment",
			"The Slums",
			"The Crematorium",
			"The Sewers",
			"The Marketplace",
			"The Ebony Barracks",
			"The Catacombs",
			"The Battlefront",
			"Lunaris Temple Level 1",
			"Lunaris Temple Level 2",
			"Solaris Temple Level 1",
			"Solaris Temple Level 2",
			"The Docks",
			"The Imperial Gardens",
			"The Library",
			"The Archives",
			"The Sceptre of God",
			"The Upper Sceptre of God",
		},
		'act4': {
			"The Aqueduct",
			"Highgate",
			"The Dried Lake",
			"The Mines Level 1",
			"The Mines Level 2",
			"The Crystal Veins",
			"Daresso's Dream",
			"Kaom's Dream",
			"The Grand Arena",
			"Kaom's Stronghold",
			"Belly of the Beast Level 1",
			"Belly of the Beast Level 2",
			"The Harvest",
			"The Ascent",
		},
		'act5': {
			"The Slave Pens",
			"Overseer's Tower",
			"The Control Blocks",
			"Oriath Square",
			"The Templar Courts",
			"The Chamber of Innocence",
			"The Torched Courts",
			"The Ruined Square",
			"The Cathedral Rooftop",
			"The Reliquary",
			"The Ossuary",
		},
		'act6': {
			"The Twilight Strand",
			"Lioneye's Watch",
			"The Coast",
			"The Tidal Island",
			"The Mud Flats",
			"The Karui Fortress",
			"The Ridge",
			"The Lower Prison",
			"Shavronne's Tower",
			"Prisoner's Gate",
			"The Western Forest",
			"The Riverways",
			"The Wetlands",
			"The Southern Forest",
			"The Cavern of Anger",
			"The Beacon",
			"The Brine King's Reef",
		},
		'act7': {
			"The Bridge Encampment",
			"The Broken Bridge",
			"The Crossroads",
			"The Fellshrine Ruins",
			"The Crypt",
			"The Chamber of Sins Level 1",
			"Maligaro's Sanctum",
			"The Chamber of Sins Level 2",
			"The Den",
			"The Ashen Fields",
			"The Northern Forest",
			"The Dread Thicket",
			"The Causeway",
			"The Vaal City",
			"The Temple of Decay Level 1",
			"The Temple of Decay Level 2",
		},
		'act8': {
			"The Sarn Ramparts",
			"The Sarn Encampment",
			"The Toxic Conduits",
			"Doedre's Cesspool",
			"The Grand Promenade",
			"The Quay",
			"The Grain Gate",
			"The Bath House",
			"The High Gardens",
			"The Imperial Fields",
			"The Lunaris Concourse",
			"The Solaris Temple Level 1",
			"The Solaris Temple Level 2",
			"The Solaris Concourse",
			"The Lunaris Temple Level 1",
			"The Lunaris Temple Level 2",
			"The Harbour Bridge",
		},
		'act9': {
			"The Blood Aqueduct",
			"Highgate",
			"The Descent",
			"The Vastiri Desert",
			"The Oasis",
			"The Foothills",
			"The Boiling Lake",
			"The Tunnel",
			"The Quarry",
			"The Refinery",
			"The Belly of the Beast",
			"The Rotting Core",
		},
		'act10': {
			"Oriath Docks",
			"The Cathedral Rooftop",
			"The Ravaged Square",
			"The Ossuary",
			"The Torched Courts",
			"The Desecrated Chambers",
			"The Reliquary",
			"The Control Blocks",
			"The Canals",
			"The Feeding Trough",
		},
		'epilogue': {
			'Oriath',
			'The Templar Laboratory',
		}
	},
	'level': {
		"1": "1", "2": "2", "3": "3", "4": "4", "5": "5", "6": "6", "7": "7", "8": "8", "9": "9", "10": "10",
		"11": "11", "12": "12", "13": "13", "14": "14", "15": "15", "16": "16", "17": "17", "18": "18", "19": "19", "20": "20",
		"21": "21", "22": "22", "23": "23", "24": "24", "25": "25", "26": "26", "27": "27", "28": "28", "29": "29", "30": "30",
		"31": "31", "32": "32", "33": "33", "34": "34", "35": "35", "36": "36", "37": "37", "38": "38", "39": "39", "40": "40",
		"41": "41", "42": "42", "43": "43", "44": "44", "45": "45", "46": "46", "47": "47", "48": "48", "49": "49", "50": "50",
		"51": "51", "52": "52", "53": "53", "54": "54", "55": "55", "56": "56", "57": "57", "58": "58", "59": "59", "60": "60",
		"61": "61", "62": "62", "63": "63", "64": "64", "65": "65", "66": "66", "67": "67", "68": "68", "69": "69", "70": "70",
		"71": "71", "72": "72", "73": "73", "74": "74", "75": "75", "76": "76", "77": "77", "78": "78", "79": "79", "80": "80",
		"81": "81", "82": "82", "83": "83", "84": "84", "85": "85", "86": "86", "87": "87", "88": "88", "89": "89", "90": "90",
		"91": "91", "92": "92", "93": "93", "94": "94", "95": "95", "96": "96", "97": "97", "98": "98", "99": "99", "100": "100",
	},
	'kill': {
		'Kitava': {
			'act5': "You have been permanently weakened by Kitava's cruel affliction. You now have -30% to all Resistances",
			'act10': "You have been permanently weakened by Kitava's merciless affliction. You now have a total of -60% to all Resistances.",
		}
	}
};

export default eventTriggers;